# Generated by Django 4.2.5 on 2023-10-06 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertising',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='advertising')),
                ('video', models.FileField(blank=True, null=True, upload_to='advertising')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=350)),
            ],
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot', models.CharField(max_length=250)),
                ('lan', models.CharField(max_length=250)),
                ('count_person', models.CharField(max_length=250)),
                ('note', models.TextField(null=True)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travels', to='user.client')),
                ('to_where', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_travels', to='main.town')),
                ('where', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travels', to='main.town')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=221)),
                ('message_id', models.CharField(max_length=221)),
                ('travel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='main.travel')),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxi_driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='user.taxidriver')),
                ('to_where', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_destinations', to='main.town')),
                ('where', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='main.town')),
            ],
        ),
    ]
