# Generated by Django 4.2.5 on 2023-10-11 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travel',
            old_name='lan',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='travel',
            old_name='lot',
            new_name='lon',
        ),
    ]
